/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjouterRouteImport } from './routes/ajouter'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as FonctionnalitesRouteImport } from './routes/fonctionnalites'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ModelesSmsRouteImport } from './routes/modeles-sms'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as TarifsRouteImport } from './routes/tarifs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjouterRoute = AjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const FonctionnalitesRoute = FonctionnalitesRouteImport.update({
  id: '/fonctionnalites',
  path: '/fonctionnalites',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelesSmsRoute = ModelesSmsRouteImport.update({
  id: '/modeles-sms',
  path: '/modeles-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajouter': typeof AjouterRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/clients': typeof ClientsRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/historique': typeof HistoriqueRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/modeles-sms': typeof ModelesSmsRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reglages': typeof ReglagesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajouter': typeof AjouterRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/clients': typeof ClientsRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/historique': typeof HistoriqueRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/modeles-sms': typeof ModelesSmsRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reglages': typeof ReglagesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajouter': typeof AjouterRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/clients': typeof ClientsRoute
  '/fonctionnalites': typeof FonctionnalitesRoute
  '/historique': typeof HistoriqueRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/modeles-sms': typeof ModelesSmsRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/reglages': typeof ReglagesRoute
  '/tarifs': typeof TarifsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajouter'
    | '/cgu'
    | '/cgv'
    | '/clients'
    | '/fonctionnalites'
    | '/historique'
    | '/mentions-legales'
    | '/modeles-sms'
    | '/politique-de-confidentialite'
    | '/reglages'
    | '/tarifs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajouter'
    | '/cgu'
    | '/cgv'
    | '/clients'
    | '/fonctionnalites'
    | '/historique'
    | '/mentions-legales'
    | '/modeles-sms'
    | '/politique-de-confidentialite'
    | '/reglages'
    | '/tarifs'
  id:
    | '__root__'
    | '/'
    | '/ajouter'
    | '/cgu'
    | '/cgv'
    | '/clients'
    | '/fonctionnalites'
    | '/historique'
    | '/mentions-legales'
    | '/modeles-sms'
    | '/politique-de-confidentialite'
    | '/reglages'
    | '/tarifs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjouterRoute: typeof AjouterRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  ClientsRoute: typeof ClientsRoute
  FonctionnalitesRoute: typeof FonctionnalitesRoute
  HistoriqueRoute: typeof HistoriqueRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ModelesSmsRoute: typeof ModelesSmsRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ReglagesRoute: typeof ReglagesRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajouter': {
      id: '/ajouter'
      path: '/ajouter'
      fullPath: '/ajouter'
      preLoaderRoute: typeof AjouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonctionnalites': {
      id: '/fonctionnalites'
      path: '/fonctionnalites'
      fullPath: '/fonctionnalites'
      preLoaderRoute: typeof FonctionnalitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeles-sms': {
      id: '/modeles-sms'
      path: '/modeles-sms'
      fullPath: '/modeles-sms'
      preLoaderRoute: typeof ModelesSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjouterRoute: AjouterRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  ClientsRoute: ClientsRoute,
  FonctionnalitesRoute: FonctionnalitesRoute,
  HistoriqueRoute: HistoriqueRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ModelesSmsRoute: ModelesSmsRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ReglagesRoute: ReglagesRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
